// 自動生成: ドリームアイランド（印刷データ準拠）
const GAME_DATA = {
 "startCost": 50,
 "rows": [
  "A",
  "B",
  "C",
  "D",
  "E"
 ],
 "cols": [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8
 ],
 "islands": [
  {
   "id": 1,
   "name": "アイランド1",
   "img": "assets/islands/island1.png",
   "terrain": {
    "A1": "beach",
    "A2": "forest",
    "A3": "forest",
    "A4": "river",
    "A5": "plain",
    "A6": "mountain",
    "A7": "forest",
    "A8": "beach",
    "B1": "forest",
    "B2": "plain",
    "B3": "mountain",
    "B4": "river",
    "B5": "forest",
    "B6": "plain",
    "B7": "forest",
    "B8": "mountain",
    "C1": "mountain",
    "C2": "forest",
    "C3": "plain",
    "C4": "river",
    "C5": "plain",
    "C6": "plain",
    "C7": "mountain",
    "C8": "plain",
    "D1": "forest",
    "D2": "plain",
    "D3": "mountain",
    "D4": "river",
    "D5": "forest",
    "D6": "plain",
    "D7": "forest",
    "D8": "mountain",
    "E1": "beach",
    "E2": "forest",
    "E3": "forest",
    "E4": "river",
    "E5": "mountain",
    "E6": "forest",
    "E7": "forest",
    "E8": "beach"
   },
   "startCells": [
    "E3",
    "E4",
    "E5"
   ],
   "vlines": [
    489,
    671,
    852,
    1034,
    1216,
    1398,
    1579,
    1761,
    1943
   ],
   "hlines": [
    286,
    469,
    644,
    817,
    997,
    1177
   ],
   "viewRect": [
    0,
    0,
    2150,
    1521
   ],
   "imgW": 2150,
   "imgH": 1521
  },
  {
   "id": 2,
   "name": "アイランド2",
   "img": "assets/islands/island2.png",
   "terrain": {
    "A1": "beach",
    "A2": "forest",
    "A3": "mountain",
    "A4": "river",
    "A5": "mountain",
    "A6": "mountain",
    "A7": "forest",
    "A8": "beach",
    "B1": "mountain",
    "B2": "plain",
    "B3": "forest",
    "B4": "river",
    "B5": "mountain",
    "B6": "plain",
    "B7": "forest",
    "B8": "mountain",
    "C1": "forest",
    "C2": "mountain",
    "C3": "river",
    "C4": "forest",
    "C5": "river",
    "C6": "plain",
    "C7": "mountain",
    "C8": "forest",
    "D1": "forest",
    "D2": "plain",
    "D3": "mountain",
    "D4": "river",
    "D5": "river",
    "D6": "mountain",
    "D7": "plain",
    "D8": "forest",
    "E1": "beach",
    "E2": "forest",
    "E3": "mountain",
    "E4": "river",
    "E5": "plain",
    "E6": "forest",
    "E7": "plain",
    "E8": "beach"
   },
   "startCells": [
    "E3",
    "E4",
    "E5"
   ],
   "vlines": [
    489,
    671,
    852,
    1034,
    1216,
    1398,
    1579,
    1761,
    1943
   ],
   "hlines": [
    286,
    469,
    644,
    817,
    997,
    1177
   ],
   "viewRect": [
    0,
    0,
    2150,
    1521
   ],
   "imgW": 2150,
   "imgH": 1521
  },
  {
   "id": 3,
   "name": "アイランド3",
   "img": "assets/islands/island3.png",
   "terrain": {
    "A1": "beach",
    "A2": "forest",
    "A3": "mountain",
    "A4": "plain",
    "A5": "forest",
    "A6": "river",
    "A7": "mountain",
    "A8": "beach",
    "B1": "forest",
    "B2": "plain",
    "B3": "mountain",
    "B4": "forest",
    "B5": "mountain",
    "B6": "river",
    "B7": "forest",
    "B8": "plain",
    "C1": "mountain",
    "C2": "forest",
    "C3": "plain",
    "C4": "mountain",
    "C5": "plain",
    "C6": "river",
    "C7": "forest",
    "C8": "mountain",
    "D1": "plain",
    "D2": "mountain",
    "D3": "forest",
    "D4": "plain",
    "D5": "forest",
    "D6": "river",
    "D7": "mountain",
    "D8": "plain",
    "E1": "beach",
    "E2": "forest",
    "E3": "plain",
    "E4": "forest",
    "E5": "mountain",
    "E6": "river",
    "E7": "forest",
    "E8": "plain"
   },
   "startCells": [
    "E3",
    "E4",
    "E5"
   ],
   "vlines": [
    489,
    671,
    852,
    1034,
    1216,
    1398,
    1579,
    1761,
    1943
   ],
   "hlines": [
    286,
    469,
    644,
    817,
    997,
    1177
   ],
   "viewRect": [
    0,
    0,
    2150,
    1521
   ],
   "imgW": 2150,
   "imgH": 1521
  },
  {
   "id": 4,
   "name": "アイランド4",
   "img": "assets/islands/island4.png",
   "terrain": {
    "A1": "river",
    "A2": "river",
    "A3": "plain",
    "A4": "mountain",
    "A5": "plain",
    "A6": "forest",
    "A7": "forest",
    "A8": "beach",
    "B1": "mountain",
    "B2": "river",
    "B3": "plain",
    "B4": "mountain",
    "B5": "forest",
    "B6": "plain",
    "B7": "plain",
    "B8": "mountain",
    "C1": "plain",
    "C2": "plain",
    "C3": "mountain",
    "C4": "river",
    "C5": "river",
    "C6": "forest",
    "C7": "plain",
    "C8": "mountain",
    "D1": "forest",
    "D2": "forest",
    "D3": "river",
    "D4": "plain",
    "D5": "mountain",
    "D6": "river",
    "D7": "forest",
    "D8": "plain",
    "E1": "beach",
    "E2": "mountain",
    "E3": "forest",
    "E4": "river",
    "E5": "mountain",
    "E6": "forest",
    "E7": "river",
    "E8": "plain"
   },
   "startCells": [
    "E3",
    "E4",
    "E5"
   ],
   "vlines": [
    489,
    671,
    852,
    1034,
    1216,
    1398,
    1579,
    1761,
    1943
   ],
   "hlines": [
    286,
    469,
    644,
    817,
    997,
    1177
   ],
   "viewRect": [
    0,
    0,
    2150,
    1521
   ],
   "imgW": 2150,
   "imgH": 1521
  },
  {
   "id": 5,
   "name": "アイランド5",
   "img": "assets/islands/island5.png",
   "terrain": {
    "A1": "beach",
    "A2": "forest",
    "A3": "plain",
    "A4": "river",
    "A5": "mountain",
    "A6": "forest",
    "A7": "mountain",
    "A8": "beach",
    "B1": "forest",
    "B2": "plain",
    "B3": "river",
    "B4": "river",
    "B5": "plain",
    "B6": "plain",
    "B7": "forest",
    "B8": "plain",
    "C1": "plain",
    "C2": "mountain",
    "C3": "river",
    "C4": "plain",
    "C5": "river",
    "C6": "mountain",
    "C7": "mountain",
    "C8": "plain",
    "D1": "forest",
    "D2": "plain",
    "D3": "forest",
    "D4": "river",
    "D5": "mountain",
    "D6": "forest",
    "D7": "plain",
    "D8": "forest",
    "E1": "beach",
    "E2": "forest",
    "E3": "mountain",
    "E4": "river",
    "E5": "river",
    "E6": "plain",
    "E7": "forest",
    "E8": "beach"
   },
   "startCells": [
    "E3",
    "E4",
    "E5"
   ],
   "vlines": [
    489,
    671,
    852,
    1034,
    1216,
    1398,
    1579,
    1761,
    1943
   ],
   "hlines": [
    286,
    469,
    644,
    817,
    997,
    1177
   ],
   "viewRect": [
    0,
    0,
    2150,
    1521
   ],
   "imgW": 2150,
   "imgH": 1521
  }
 ],
 "attractions": [
  {
   "id": 1,
   "name": "ハンバーガーショップ",
   "cat": "飲食",
   "color": "red",
   "E": 2,
   "N": 0,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ハンバーガーショップ.png",
   "emoji": "🍔"
  },
  {
   "id": 2,
   "name": "ピザレストラン",
   "cat": "飲食",
   "color": "red",
   "E": 2,
   "N": 0,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ピザレストラン.png",
   "emoji": "🍔"
  },
  {
   "id": 3,
   "name": "和食レストラン",
   "cat": "飲食",
   "color": "red",
   "E": 2,
   "N": 1,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/和食レストラン.png",
   "emoji": "🍔"
  },
  {
   "id": 4,
   "name": "カフェ",
   "cat": "飲食",
   "color": "red",
   "E": 2,
   "N": 1,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/カフェ.png",
   "emoji": "🍔"
  },
  {
   "id": 5,
   "name": "ポップコーンワゴン",
   "cat": "飲食",
   "color": "red",
   "E": 1,
   "N": 0,
   "C": 1,
   "size": 0.5,
   "fw": 1,
   "fh": 1,
   "mini": true,
   "img": "assets/chips_print/ポップコーンワゴン.png",
   "emoji": "🍿"
  },
  {
   "id": 6,
   "name": "アイスクリームスタンド",
   "cat": "飲食",
   "color": "red",
   "E": 1,
   "N": 0,
   "C": 1,
   "size": 0.5,
   "fw": 1,
   "fh": 1,
   "mini": true,
   "img": "assets/chips_print/アイスクリームスタンド.png",
   "emoji": "🍦"
  },
  {
   "id": 7,
   "name": "チュロス屋台",
   "cat": "飲食",
   "color": "red",
   "E": 1,
   "N": 0,
   "C": 1,
   "size": 0.5,
   "fw": 1,
   "fh": 1,
   "mini": true,
   "img": "assets/chips_print/チュロス屋台.png",
   "emoji": "🥨"
  },
  {
   "id": 8,
   "name": "フードコート",
   "cat": "飲食",
   "color": "red",
   "E": 3,
   "N": 0,
   "C": 3,
   "size": 2,
   "fw": 1,
   "fh": 2,
   "mini": false,
   "img": "assets/chips_print/フードコート.png",
   "emoji": "🍔"
  },
  {
   "id": 9,
   "name": "キャラクターレストラン",
   "cat": "飲食",
   "color": "red",
   "E": 4,
   "N": 0,
   "C": 4,
   "size": 1.5,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/キャラクターレストラン.png",
   "emoji": "🍔"
  },
  {
   "id": 10,
   "name": "高級レストラン",
   "cat": "飲食",
   "color": "red",
   "E": 3,
   "N": 1,
   "C": 5,
   "size": 2,
   "fw": 1,
   "fh": 2,
   "mini": false,
   "img": "assets/chips_print/高級レストラン.png",
   "emoji": "🍔"
  },
  {
   "id": 11,
   "name": "ビーチバー",
   "cat": "飲食",
   "color": "red",
   "E": 3,
   "N": 2,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ビーチバー.png",
   "emoji": "🍔"
  },
  {
   "id": 12,
   "name": "シーフードレストラン",
   "cat": "飲食",
   "color": "red",
   "E": 3,
   "N": 3,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/シーフードレストラン.png",
   "emoji": "🍔"
  },
  {
   "id": 13,
   "name": "ジャングルカフェ",
   "cat": "飲食",
   "color": "red",
   "E": 2,
   "N": 3,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ジャングルカフェ.png",
   "emoji": "🍔"
  },
  {
   "id": 14,
   "name": "フルーツスタンド",
   "cat": "飲食",
   "color": "red",
   "E": 1,
   "N": 3,
   "C": 1,
   "size": 0.5,
   "fw": 1,
   "fh": 1,
   "mini": true,
   "img": "assets/chips_print/フルーツスタンド.png",
   "emoji": "🍓"
  },
  {
   "id": 15,
   "name": "ラーメン屋",
   "cat": "飲食",
   "color": "red",
   "E": 2,
   "N": 0,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ラーメン屋.png",
   "emoji": "🍔"
  },
  {
   "id": 16,
   "name": "ジェットコースター",
   "cat": "乗り物",
   "color": "blue",
   "E": 6,
   "N": 0,
   "C": 5,
   "size": 3,
   "fw": 1,
   "fh": 2,
   "mini": false,
   "img": "assets/chips_print/ジェットコースター.png",
   "emoji": "🎢"
  },
  {
   "id": 17,
   "name": "観覧車",
   "cat": "乗り物",
   "color": "blue",
   "E": 3,
   "N": 2,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/観覧車.png",
   "emoji": "🎢"
  },
  {
   "id": 18,
   "name": "メリーゴーランド",
   "cat": "乗り物",
   "color": "blue",
   "E": 2,
   "N": 0,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/メリーゴーランド.png",
   "emoji": "🎢"
  },
  {
   "id": 19,
   "name": "ゴーカート",
   "cat": "乗り物",
   "color": "blue",
   "E": 3,
   "N": 0,
   "C": 3,
   "size": 2,
   "fw": 1,
   "fh": 2,
   "mini": false,
   "img": "assets/chips_print/ゴーカート.png",
   "emoji": "🎢"
  },
  {
   "id": 20,
   "name": "急流すべり",
   "cat": "乗り物",
   "color": "blue",
   "E": 4,
   "N": 2,
   "C": 4,
   "size": 2,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/急流すべり.png",
   "emoji": "🎢"
  },
  {
   "id": 21,
   "name": "フリーフォール",
   "cat": "乗り物",
   "color": "blue",
   "E": 5,
   "N": 0,
   "C": 4,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/フリーフォール.png",
   "emoji": "🎢"
  },
  {
   "id": 22,
   "name": "回転系ライド",
   "cat": "乗り物",
   "color": "blue",
   "E": 3,
   "N": 0,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/回転系ライド.png",
   "emoji": "🎢"
  },
  {
   "id": 23,
   "name": "ダークライド",
   "cat": "乗り物",
   "color": "blue",
   "E": 4,
   "N": 0,
   "C": 4,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ダークライド.png",
   "emoji": "🎢"
  },
  {
   "id": 24,
   "name": "シューティングライド",
   "cat": "乗り物",
   "color": "blue",
   "E": 4,
   "N": 0,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/シューティングライド.png",
   "emoji": "🎢"
  },
  {
   "id": 25,
   "name": "ミニトレイン",
   "cat": "乗り物",
   "color": "blue",
   "E": 2,
   "N": 2,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ミニトレイン.png",
   "emoji": "🎢"
  },
  {
   "id": 26,
   "name": "ジップライン",
   "cat": "乗り物",
   "color": "blue",
   "E": 4,
   "N": 4,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ジップライン.png",
   "emoji": "🎢"
  },
  {
   "id": 27,
   "name": "カヌーライド",
   "cat": "乗り物",
   "color": "blue",
   "E": 3,
   "N": 4,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/カヌーライド.png",
   "emoji": "🎢"
  },
  {
   "id": 28,
   "name": "ボートツアー",
   "cat": "乗り物",
   "color": "blue",
   "E": 3,
   "N": 5,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ボートツアー.png",
   "emoji": "🎢"
  },
  {
   "id": 29,
   "name": "サファリカー",
   "cat": "乗り物",
   "color": "blue",
   "E": 2,
   "N": 2,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/サファリカー.png",
   "emoji": "🎢"
  },
  {
   "id": 30,
   "name": "水上バイク",
   "cat": "乗り物",
   "color": "blue",
   "E": 4,
   "N": 2,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/水上バイク.png",
   "emoji": "🎢"
  },
  {
   "id": 31,
   "name": "吊り橋アドベンチャー",
   "cat": "乗り物",
   "color": "blue",
   "E": 3,
   "N": 4,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/吊り橋アドベンチャー.png",
   "emoji": "🎢"
  },
  {
   "id": 32,
   "name": "潜水艦ライド",
   "cat": "乗り物",
   "color": "blue",
   "E": 3,
   "N": 2,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/潜水艦ライド.png",
   "emoji": "🎢"
  },
  {
   "id": 33,
   "name": "シュノーケリング",
   "cat": "アウトドア",
   "color": "green",
   "E": 3,
   "N": 5,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/シュノーケリング.png",
   "emoji": "🏕️"
  },
  {
   "id": 34,
   "name": "ダイビング",
   "cat": "アウトドア",
   "color": "green",
   "E": 4,
   "N": 5,
   "C": 4,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ダイビング.png",
   "emoji": "🏕️"
  },
  {
   "id": 35,
   "name": "釣り体験",
   "cat": "アウトドア",
   "color": "green",
   "E": 2,
   "N": 4,
   "C": 1,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/釣り体験.png",
   "emoji": "🏕️"
  },
  {
   "id": 36,
   "name": "キャンプ場",
   "cat": "アウトドア",
   "color": "green",
   "E": 2,
   "N": 5,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/キャンプ場.png",
   "emoji": "🏕️"
  },
  {
   "id": 37,
   "name": "BBQエリア",
   "cat": "アウトドア",
   "color": "green",
   "E": 3,
   "N": 3,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/BBQエリア.png",
   "emoji": "🏕️"
  },
  {
   "id": 38,
   "name": "サバイバル体験",
   "cat": "アウトドア",
   "color": "green",
   "E": 4,
   "N": 5,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/サバイバル体験.png",
   "emoji": "🏕️"
  },
  {
   "id": 39,
   "name": "ジャングルトレッキング",
   "cat": "アウトドア",
   "color": "green",
   "E": 3,
   "N": 5,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ジャングルトレッキング.png",
   "emoji": "🏕️"
  },
  {
   "id": 40,
   "name": "ナイトツアー",
   "cat": "アウトドア",
   "color": "green",
   "E": 4,
   "N": 5,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ナイトツアー.png",
   "emoji": "🏕️"
  },
  {
   "id": 41,
   "name": "バードウォッチング",
   "cat": "アウトドア",
   "color": "green",
   "E": 2,
   "N": 5,
   "C": 1,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/バードウォッチング.png",
   "emoji": "🏕️"
  },
  {
   "id": 42,
   "name": "洞窟探検",
   "cat": "アウトドア",
   "color": "green",
   "E": 4,
   "N": 5,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/洞窟探検.png",
   "emoji": "🏕️"
  },
  {
   "id": 43,
   "name": "セントラルガーデン",
   "cat": "アウトドア",
   "color": "green",
   "E": 4,
   "N": 4,
   "C": 3,
   "size": 1,
   "fw": 2,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/セントラルガーデン.png",
   "emoji": "🏕️"
  },
  {
   "id": 44,
   "name": "フラワーガーデン",
   "cat": "アウトドア",
   "color": "green",
   "E": 1,
   "N": 3,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/フラワーガーデン.png",
   "emoji": "🏕️"
  },
  {
   "id": 45,
   "name": "ミニ動物園",
   "cat": "アウトドア",
   "color": "green",
   "E": 1,
   "N": 3,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ミニ動物園.png",
   "emoji": "🏕️"
  },
  {
   "id": 46,
   "name": "イルカウォッチング",
   "cat": "アウトドア",
   "color": "green",
   "E": 1,
   "N": 5,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/イルカウォッチング.png",
   "emoji": "🏕️"
  },
  {
   "id": 47,
   "name": "3Dシアター",
   "cat": "シアター",
   "color": "purple",
   "E": 4,
   "N": 0,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/3Dシアター.png",
   "emoji": "🎬"
  },
  {
   "id": 48,
   "name": "4Dシアター",
   "cat": "シアター",
   "color": "purple",
   "E": 5,
   "N": 0,
   "C": 5,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/4Dシアター.png",
   "emoji": "🎬"
  },
  {
   "id": 49,
   "name": "プラネタリウム",
   "cat": "シアター",
   "color": "purple",
   "E": 3,
   "N": 3,
   "C": 4,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/プラネタリウム.png",
   "emoji": "🎬"
  },
  {
   "id": 50,
   "name": "VRシアター",
   "cat": "シアター",
   "color": "purple",
   "E": 5,
   "N": 0,
   "C": 4,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/VRシアター.png",
   "emoji": "🎬"
  },
  {
   "id": 51,
   "name": "屋外シアター",
   "cat": "シアター",
   "color": "purple",
   "E": 3,
   "N": 2,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/屋外シアター.png",
   "emoji": "🎬"
  },
  {
   "id": 52,
   "name": "自然解説シアター",
   "cat": "シアター",
   "color": "purple",
   "E": 2,
   "N": 4,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/自然解説シアター.png",
   "emoji": "🎬"
  },
  {
   "id": 53,
   "name": "パレード",
   "cat": "ショー",
   "color": "purple",
   "E": 5,
   "N": 0,
   "C": 4,
   "size": 2,
   "fw": 1,
   "fh": 2,
   "mini": false,
   "img": "assets/chips_print/パレード.png",
   "emoji": "🎭"
  },
  {
   "id": 54,
   "name": "花火ショー",
   "cat": "ショー",
   "color": "purple",
   "E": 5,
   "N": 1,
   "C": 5,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/花火ショー.png",
   "emoji": "🎭"
  },
  {
   "id": 55,
   "name": "キャラクターショー",
   "cat": "ショー",
   "color": "purple",
   "E": 4,
   "N": 0,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/キャラクターショー.png",
   "emoji": "🎭"
  },
  {
   "id": 56,
   "name": "ステージショー",
   "cat": "ショー",
   "color": "purple",
   "E": 4,
   "N": 0,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ステージショー.png",
   "emoji": "🎭"
  },
  {
   "id": 57,
   "name": "スタントショー",
   "cat": "ショー",
   "color": "purple",
   "E": 5,
   "N": 0,
   "C": 4,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/スタントショー.png",
   "emoji": "🎭"
  },
  {
   "id": 58,
   "name": "マジックショー",
   "cat": "ショー",
   "color": "purple",
   "E": 4,
   "N": 0,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/マジックショー.png",
   "emoji": "🎭"
  },
  {
   "id": 59,
   "name": "ビーチライブ",
   "cat": "ショー",
   "color": "purple",
   "E": 4,
   "N": 2,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ビーチライブ.png",
   "emoji": "🎭"
  },
  {
   "id": 60,
   "name": "ファイヤーダンス",
   "cat": "ショー",
   "color": "purple",
   "E": 4,
   "N": 2,
   "C": 2,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ファイヤーダンス.png",
   "emoji": "🎭"
  },
  {
   "id": 61,
   "name": "イルミネーション",
   "cat": "ショー",
   "color": "purple",
   "E": 4,
   "N": 1,
   "C": 3,
   "size": 2,
   "fw": 1,
   "fh": 2,
   "mini": false,
   "img": "assets/chips_print/イルミネーション.png",
   "emoji": "🎭"
  },
  {
   "id": 62,
   "name": "動物ショー",
   "cat": "ショー",
   "color": "purple",
   "E": 3,
   "N": 3,
   "C": 3,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/動物ショー.png",
   "emoji": "🎭"
  },
  {
   "id": 63,
   "name": "噴水ショー",
   "cat": "ショー",
   "color": "purple",
   "E": 3,
   "N": 0,
   "C": 8,
   "size": 2,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/噴水ショー.png",
   "emoji": "🎭"
  },
  {
   "id": 64,
   "name": "射的",
   "cat": "ミニゲーム",
   "color": "gold",
   "E": 2,
   "N": 0,
   "C": 1,
   "size": 0.5,
   "fw": 1,
   "fh": 1,
   "mini": true,
   "img": "assets/chips_print/射的.png",
   "emoji": "🎯"
  },
  {
   "id": 65,
   "name": "輪投げ",
   "cat": "ミニゲーム",
   "color": "gold",
   "E": 1,
   "N": 0,
   "C": 1,
   "size": 0.5,
   "fw": 1,
   "fh": 1,
   "mini": true,
   "img": "assets/chips_print/輪投げ.png",
   "emoji": "⭕"
  },
  {
   "id": 66,
   "name": "ボール投げ",
   "cat": "ミニゲーム",
   "color": "gold",
   "E": 2,
   "N": 0,
   "C": 1,
   "size": 0.5,
   "fw": 1,
   "fh": 1,
   "mini": true,
   "img": "assets/chips_print/ボール投げ.png",
   "emoji": "⚾"
  },
  {
   "id": 67,
   "name": "くじ引き",
   "cat": "ミニゲーム",
   "color": "gold",
   "E": 1,
   "N": 0,
   "C": 1,
   "size": 0.5,
   "fw": 1,
   "fh": 1,
   "mini": true,
   "img": "assets/chips_print/くじ引き.png",
   "emoji": "🎫"
  },
  {
   "id": 68,
   "name": "グッズショップ",
   "cat": "ミニゲーム",
   "color": "gold",
   "E": 1,
   "N": 0,
   "C": 1,
   "size": 0.5,
   "fw": 1,
   "fh": 1,
   "mini": true,
   "img": "assets/chips_print/グッズショップ.png",
   "emoji": "🛍️"
  },
  {
   "id": 69,
   "name": "道①",
   "cat": "インフラ",
   "color": "gray",
   "E": 1,
   "N": 0,
   "C": 1,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/道①.png",
   "emoji": "🏛️"
  },
  {
   "id": 70,
   "name": "道②",
   "cat": "インフラ",
   "color": "gray",
   "E": 1,
   "N": 0,
   "C": 1,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/道②.png",
   "emoji": "🏛️"
  },
  {
   "id": 71,
   "name": "道③",
   "cat": "インフラ",
   "color": "gray",
   "E": 1,
   "N": 0,
   "C": 1,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/道③.png",
   "emoji": "🏛️"
  },
  {
   "id": 72,
   "name": "ゲート①",
   "cat": "インフラ",
   "color": "gray",
   "E": 2,
   "N": 0,
   "C": 1,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ゲート①.png",
   "emoji": "🏛️"
  },
  {
   "id": 73,
   "name": "ゲート②",
   "cat": "インフラ",
   "color": "gray",
   "E": 2,
   "N": 0,
   "C": 1,
   "size": 1,
   "fw": 1,
   "fh": 1,
   "mini": false,
   "img": "assets/chips_print/ゲート②.png",
   "emoji": "🏛️"
  },
  {
   "id": 74,
   "name": "海賊砦",
   "cat": "インフラ",
   "color": "gray",
   "E": 4,
   "N": 2,
   "C": 6,
   "size": 2,
   "fw": 2,
   "fh": 2,
   "mini": false,
   "img": "assets/specials/fort.png",
   "emoji": "🏛️"
  },
  {
   "id": 75,
   "name": "お城",
   "cat": "インフラ",
   "color": "gray",
   "E": 4,
   "N": 2,
   "C": 6,
   "size": 2,
   "fw": 2,
   "fh": 2,
   "mini": false,
   "img": "assets/specials/castle.png",
   "emoji": "🏛️"
  },
  {
   "id": 76,
   "name": "プロジェクションマッピング",
   "cat": "インフラ",
   "color": "gray",
   "E": 6,
   "N": 0,
   "C": 15,
   "size": 2,
   "fw": 2,
   "fh": 2,
   "mini": false,
   "img": "assets/specials/projection.png",
   "emoji": "🏛️"
  }
 ],
 "sponsors": [
  {
   "id": "food",
   "name": "飲食メーカー",
   "img": "assets/sponsors/food.png",
   "effect": "飲食店（赤）の建設コスト -1（コスト2以上）",
   "color": "red"
  },
  {
   "id": "build",
   "name": "建設会社",
   "img": "assets/sponsors/build.png",
   "effect": "乗り物（青）の建設コスト -1（コスト2以上）",
   "color": "blue"
  },
  {
   "id": "event",
   "name": "イベント会社",
   "img": "assets/sponsors/event.png",
   "effect": "ショー（紫）の建設コスト -1（コスト2以上）",
   "color": "purple"
  },
  {
   "id": "outdoor",
   "name": "アウトドアグッズ会社",
   "img": "assets/sponsors/outdoor.png",
   "effect": "アウトドア（緑）の建設コスト -1（コスト2以上）",
   "color": "green"
  }
 ],
 "terrainRules": {
  "beach": {
   "label": "ビーチ",
   "color": "red",
   "desc": "飲食店の建設コスト -1"
  },
  "forest": {
   "label": "森",
   "color": "green",
   "desc": "アウトドアの建設コスト -1"
  },
  "mountain": {
   "label": "山",
   "color": "blue",
   "desc": "乗り物の建設コスト -1"
  },
  "river": {
   "label": "川",
   "color": "red",
   "desc": "飲食店の建設コスト -1"
  },
  "plain": {
   "label": "平地",
   "color": "purple",
   "desc": "ショーの建設コスト -1"
  }
 },
 "matrix": {
  "labels": [
   "0-30",
   "31-40",
   "41-50",
   "51-60",
   "61~"
  ],
  "grid": [
   [
    "未発展",
    "ローカルパーク",
    "ネイチャー志向",
    "ネイチャーリゾート",
    "秘境リゾート"
   ],
   [
    "ローカルパーク",
    "バランス型",
    "バランス型",
    "ネイチャーリゾート",
    "ネイチャーリゾート"
   ],
   [
    "準エンタメ型",
    "バランス型",
    "バランス型",
    "調和の楽園",
    "調和の楽園"
   ],
   [
    "エンタメ帝国",
    "人気テーマパーク",
    "調和の楽園",
    "調和の楽園",
    "世界遺産級テーマパーク"
   ],
   [
    "エンタメ帝国",
    "エンタメ帝国",
    "人気テーマパーク",
    "調和の楽園",
    "世界遺産級テーマパーク"
   ]
  ]
 },
 "descs": {
  "未発展": "まだ開発が始まったばかりの無人島。これからが本番です",
  "ローカルパーク": "地域密着型の小規模パーク。地元の人々に親しまれています",
  "ネイチャー志向": "自然をいかした穏やかな島。のんびり過ごせます",
  "ネイチャーリゾート": "自然と触れ合える癒しの空間。ゆったりとした時間が流れます",
  "秘境リゾート": "知る人ぞ知る特別な場所。静かな魅力に満ちています",
  "準エンタメ型": "遊びごたえが出てきた発展途中のパーク",
  "エンタメ帝国": "圧倒的なアトラクション群で来場者を魅了する一大娯楽施設",
  "人気テーマパーク": "多くの人が訪れる定番の人気スポット",
  "バランス型": "誰もが楽しめる安定した魅力。長く愛されるテーマパーク",
  "調和の楽園": "自然とエンタメが高いレベルで融合した理想的なパーク",
  "世界遺産級テーマパーク": "世界中から評価される究極のテーマパーク"
 },
 "bands": [
  30,
  40,
  50,
  60
 ]
};
